[project]
name = "ai-deep-research-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "composio>=0.9.4",
    "composio-langchain>=0.9.4",
    "deepagents>=0.3.0",
    "streamlit>=1.52.1",
]
